name: CI workflow

on:
    push:
        branches: [ master, develop ]
    pull_request:
        branches: [ master, develop ]

permissions:
    id-token: write
    contents: read

jobs:
    build-and-push-images:
        name: Build a JAR in spring boot using springboot and push it to ECR
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Cache Maven dependencies
                uses: actions/cache@v3
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'

            -   name: Clean and install Maven
                run: mvn clean install

            -   name: Login to docker registry
                uses: docker/login-action@v3
                with:
                    username: ${{secrets.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}

            -   name: build and push docker image to registry
                uses: docker/build-push-action@v5
                with:
                    push: true
                    tags: jukibach/nozma-be:latest
